name: sahaayak_ai
description: AI-powered teaching assistant for rural Indian schools
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^3.1.2
  cached_network_image: ^3.3.1
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Media & Files
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  
  # Audio
  flutter_sound: ^9.2.13
  audio_waveforms: ^1.0.5
  just_audio: ^0.9.36
  
  # Permissions
  permission_handler: ^11.2.0
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  equatable: ^2.0.5
  
  # Animations
  flutter_animate: ^4.5.0
  rive: ^0.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/illustrations/
  
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700 